name: docker
on:
  push:
    branches:
      - main

jobs:
  build:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.device }}
    environment:
      name: docker
      url: https://hub.docker.com/r/hiyouga/llamafactory
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          docker-images: false
          tool-cache: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - id: version
        name: Get llamafactory version
        run: 'echo "tag=$(python setup.py --version | sed ''s/\.dev0//'')" >> "$GITHUB_OUTPUT"

          '
      - id: measurement-5
        name: Record Measurement After Get llamafactory version
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Get llamafactory version
          task: get-measurement
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - if: ${{ github.event_name != 'pull_request' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ vars.DOCKERHUB_USERNAME }}
      - if: ${{ github.event_name != 'pull_request' && matrix.device == 'npu' }}
        name: Login to Quay
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.QUAY_ASCEND_TOKEN }}
          registry: quay.io
          username: ${{ vars.QUAY_ASCEND_USERNAME }}
      - if: ${{ matrix.device == 'cuda' }}
        name: Build and push Docker image (CUDA)
        uses: docker/build-push-action@v6
        with:
          build-args: 'EXTRAS=metrics,deepspeed,liger-kernel

            '
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ./docker/docker-cuda/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: 'docker.io/hiyouga/llamafactory:latest

            docker.io/hiyouga/llamafactory:${{ steps.version.outputs.tag }}

            '
      - if: ${{ matrix.device == 'npu' }}
        name: Build and push Docker image (NPU)
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ./docker/docker-npu/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: 'docker.io/hiyouga/llamafactory:latest-npu-a2

            docker.io/hiyouga/llamafactory:${{ steps.version.outputs.tag }}-npu-a2

            quay.io/ascend/llamafactory:latest-npu-a2

            quay.io/ascend/llamafactory:${{ steps.version.outputs.tag }}-npu-a2

            '
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        device:
          - cuda
          - npu
